"""Stage 3B: Schedule Packing (baseline).

Staggers route departures to spread coverage over the revisit window Θ.
"""

from __future__ import annotations

from typing import List, Tuple
from dataclasses import dataclass

from .core.route import Route
from .config.parameters import SystemParameters

__all__ = [
    "pack_departures_staggered",
    "ScheduleSummary",
]


@dataclass
class ScheduleSummary:
    """Key metrics needed for Stage-2 feedback and later stages."""

    longest_loop_time: float
    n_surge: int  # Simultaneous UAVs on pad estimated from Δ_swap rule
    β_adapt: float  # Adaptive spare floor suggestion


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------


def pack_departures_staggered(
    routes: List[Route],
    max_revisit_gap: float,
    swap_slot: float = 60.0,
    batch_size: int = 4,
    batch_period: float = 30.0,
) -> ScheduleSummary:
    """Assign departure times using batch scheduler v2.

    Args:
        routes: List of routes generated by Stage-3A.
        max_revisit_gap: Θ (seconds) from STL contract.
        swap_slot: Δ_swap – battery hot-swap time.
        batch_size: Number of UAVs per departure batch.
        batch_period: Time between batch departures (seconds).

    Returns:
        ScheduleSummary (longest loop, n_surge, β_adapt)
    """

    n = len(routes)
    if n == 0:
        raise ValueError("No routes to schedule")

    # Batch scheduler v2: Spread departures to prevent simultaneous battery drain
    # Strategy: Launch batches with longer gaps to stagger when UAVs need to return
    
    # Calculate how many batches we need
    num_batches = (n + batch_size - 1) // batch_size  # ceiling division
    
    for i, route in enumerate(routes):
        batch_idx = i // batch_size
        within_batch_idx = i % batch_size
        
        # Each batch starts at longer intervals to spread battery drain
        batch_start_time = batch_idx * batch_period
        
        # Within each batch, launch with small gaps (just for pad logistics)
        within_batch_gap = 5.0  # small gap within batch for pad clearance
        route.departure_time = batch_start_time + within_batch_idx * within_batch_gap
    
    # Debug: Print departure schedule
    print(f"   📅 Batch Schedule (batch_size={batch_size}, batch_period={batch_period}s):")
    for i, route in enumerate(routes):
        batch_idx = i // batch_size
        print(f"      UAV {i:2d}: t={route.departure_time:5.1f}s (batch {batch_idx})")
    
    longest_loop = max((r.loop_time or 0.0) for r in routes)

    # Estimate simultaneous pads demand
    n_surge = int((swap_slot / longest_loop) * n) + 1

    β_adapt = n_surge / (n + n_surge)

    return ScheduleSummary(longest_loop, n_surge, β_adapt)


# Convenience wrapper

def schedule_from_config(
    config: SystemParameters,
    routes: List[Route],
):
    """Pack departures using parameters from *SystemParameters*."""

    return pack_departures_staggered(
        routes,
        max_revisit_gap=config.stl.max_revisit_gap,
        swap_slot=config.battery.hot_swap_time,
        batch_size=config.optimization.batch_size,
        batch_period=config.optimization.batch_period,
    ) 